title: "[Bug]: "
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please search for existing Discussions and Issues before opening a new one.
  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: Detailed description of the issue.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment / Versions
      description: OS version, Gnosis VPN version, and other relevant environment details.
    validations:
      required: true
  - type: checkboxes
    id: acknowledgement
    attributes:
      label: Acknowledgement
      options:
        - label: I have searched for existing issues and discussions.
          required: true
