version = 6

[pix_strategy]
price_per_byte = "0.000000000000000001 wxHOPR"
max_ssa_allocation = "0.000000001 wxHOPR"
deposit_buffer_period = "500ms"
max_deposit_tracking_time = "60s"
max_deposit_retries = 3
