name: Merge PR
on:
  pull_request:
    types:
      - closed
      # - synchronize
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: merge
  cancel-in-progress: false
jobs:
  build-binary:
    name: Build
    uses: ./.github/workflows/build-binary.yaml
    with:
      version_type: pr
    secrets: inherit
