name: Merge PR
on:
  pull_request:
    types:
      - closed
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: merge
  cancel-in-progress: false
jobs:
  build-binaries:
    name: Build
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build-binary.yaml
    with:
      version_type: pr
    secrets: inherit
  snapshot-build:
    name: Snapshot build
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'snapshot-build')
    runs-on: depot-ubuntu-22.04-4
    needs:
      - build-binaries
    permissions:
      contents: read
    steps:
      - name: Trigger snapshot build
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          repository: gnosis/gnosis_vpn
          event-type: snapshot_build
