name: Nightly Build
on:
  pull_request:
    types:
      - synchronize
  repository_dispatch:
    types: [snapshot_build]
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2 AM UTC
concurrency:
  group: nightly-build
  cancel-in-progress: false
jobs:
  build_binary:
    name: Build
    uses: ./.github/workflows/build-binary.yaml
    with:
      version_type: snapshot
    secrets: inherit
  post_build:
    name: Post build
    runs-on: depot-ubuntu-22.04-4
    if: needs.build_binary.outputs.SNAPSHOT_TRIGGERED == 'true'
    needs:
      - build_binary
    env:
      GNOSISVPN_PACKAGE_VERSION: ${{ needs.build_binary.outputs.GNOSISVPN_PACKAGE_VERSION }}
      LATEST_GNOSISVPN_PACKAGE_PR_VERSION: ${{ needs.build_binary.outputs.LATEST_GNOSISVPN_PACKAGE_PR_VERSION }}
      GNOSISVPN_CLI_VERSION: ${{ needs.build_binary.outputs.GNOSISVPN_CLI_VERSION }}
      GNOSISVPN_APP_VERSION: ${{ needs.build_binary.outputs.GNOSISVPN_APP_VERSION }}
      PREVIOUS_GNOSISVPN_PACKAGE_PR_VERSION: ${{ vars.GNOSISVPN_PACKAGE_PR_VERSION }}
      GNOSISVPN_PREVIOUS_CLI_VERSION: ${{ vars.GNOSISVPN_CLI_PR_VERSION }}
      GNOSISVPN_PREVIOUS_APP_VERSION: ${{ vars.GNOSISVPN_APP_PR_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Display versions
        run: |
          echo "- Package version: $GNOSISVPN_PACKAGE_VERSION" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "- Client version: v$GNOSISVPN_CLI_VERSION" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "- App version: v$GNOSISVPN_APP_VERSION" | tee -a "$GITHUB_STEP_SUMMARY"
      - name: Generate Changelog
        run: nix develop -c ./scripts/generate-changelog.ts
        env:
          GH_TOKEN: ${{ github.token }}
          GNOSISVPN_PACKAGE_VERSION: ${{ env.LATEST_GNOSISVPN_PACKAGE_PR_VERSION }}
          GNOSISVPN_PREVIOUS_PACKAGE_VERSION: ${{ env.PREVIOUS_GNOSISVPN_PACKAGE_PR_VERSION }}
          GNOSISVPN_CHANGELOG_FORMAT: zulip
      - name: Prepare notification message
        run: |
          # Store content in environment variable for the Zulip action
          {
            echo "NOTIFICATION_CONTENT<<EOF"
            cat build/changelog/changelog
            echo "EOF"
          } >> $GITHUB_ENV
      - name: Notify release
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ secrets.ZULIP_EMAIL }}
          organization-url: "https://hopr.zulipchat.com"
          type: "stream"
          to: "GnosisVPN"
          topic: "Releases"
          content: ${{ env.NOTIFICATION_CONTENT }}
      - name: Update latest merged PR variables
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${LATEST_GNOSISVPN_PACKAGE_PR_VERSION}" != "${PREVIOUS_GNOSISVPN_PACKAGE_PR_VERSION}" ]]; then
            echo "New merged PR found for gnosis_vpn: ${LATEST_GNOSISVPN_PACKAGE_PR_VERSION}"
            gh variable set GNOSISVPN_PACKAGE_PR_VERSION --repo ${{ github.repository }} --body "${LATEST_GNOSISVPN_PACKAGE_PR_VERSION}"
          fi
          if [[ "${GNOSISVPN_CLI_VERSION}" != "${GNOSISVPN_PREVIOUS_CLI_VERSION}" ]]; then
            echo "New merged PR found for gnosis_vpn-client: ${GNOSISVPN_CLI_VERSION}"
            gh variable set GNOSISVPN_CLI_PR_VERSION --repo ${{ github.repository }} --body "${GNOSISVPN_CLI_VERSION}"
          fi
          if [[ "${GNOSISVPN_APP_VERSION}" != "${GNOSISVPN_PREVIOUS_APP_VERSION}" ]]; then
            echo "New merged PR found for gnosis_vpn-app: ${GNOSISVPN_APP_VERSION}"
            gh variable set GNOSISVPN_APP_PR_VERSION --repo ${{ github.repository }} --body "${GNOSISVPN_APP_VERSION}"
          fi
