name: PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
permissions:
  contents: read
  id-token: write
concurrency:
  group: pr-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: false
jobs:
  build-binary:
    name: Build
    uses: ./.github/workflows/build-binary.yaml
    with:
      version_type: commit
    secrets: inherit
  checks:
    name: Checks
    runs-on: depot-ubuntu-22.04-4
    steps:
      - name: Check flake
        uses: hoprnet/hopr-workflows/actions/nix-action@c2aca7e56d25c4a786049ccf816c7f1af8721de8 # nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
          cachix_cache_name: gnosis-vpn
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          command: nix flake check -L --show-trace --max-jobs 1
