name: Publish install.sh
on:
  push:
    branches: [main]
    paths:
      - install/linux.sh
      - .github/workflows/publish-install.sh.yaml
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
concurrency:
  group: publish-install.sh
  cancel-in-progress: false
jobs:
  publish:
    name: Upload install.sh to download.gnosisvpn.io
    runs-on: depot-ubuntu-22.04-4
    steps:
      - name: Checkout repository
        uses: actions/checkout@eedb4b7701714299852ca5243f1544b817653f33 # hopr-workflows v0.11.1
      - name: Setup GCP
        uses: hoprnet/hopr-workflows/actions/setup-gcp@eedb4b7701714299852ca5243f1544b817653f33 # hopr-workflows v0.11.1
        with:
          workload_identity_provider: projects/656686060169/locations/global/workloadIdentityPools/gnosisvpn-gh-pool/providers/github-provider
          service_account: download-gnosisvpn-gh-sa@gnosisvpn-production.iam.gserviceaccount.com
          install_sdk: true
      - name: Upload install.sh
        run: |
          gsutil -h "Content-Type:text/x-shellscript; charset=utf-8" \
                 -h "Cache-Control:public, max-age=300" \
                 cp install/linux.sh gs://download.gnosisvpn.io/linux/install.sh
