name: Publish install.sh
on:
  push:
    branches: [main]
    paths:
      - install/linux.sh
      - .github/workflows/publish-install.sh.yaml
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
concurrency:
  group: publish-install.sh
  cancel-in-progress: false
jobs:
  publish:
    name: Upload install.sh to download.gnosisvpn.io
    runs-on: depot-ubuntu-22.04-4
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup GCP
        uses: hoprnet/hopr-workflows/actions/setup-gcp@ade4bbd75f7204255c61d19c23f67d3da221e7d2 # setup-gcp-v4
        with:
          workload_identity_provider: projects/656686060169/locations/global/workloadIdentityPools/gnosisvpn-gh-pool/providers/github-provider
          service_account: download-gnosisvpn-gh-sa@gnosisvpn-production.iam.gserviceaccount.com
          install_sdk: true
      - name: Upload install.sh
        run: |
          gsutil -h "Content-Type:text/x-shellscript; charset=utf-8" \
                 -h "Cache-Control:public, max-age=300" \
                 cp install/linux.sh gs://download.gnosisvpn.io/linux/install.sh
