name: Close release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Version type after release
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major
permissions:
  contents: read
  id-token: write
concurrency:
  group: release
  cancel-in-progress: false
jobs:
  build_binary:
    name: Build
    uses: ./.github/workflows/build-binary.yaml
    with:
      version_type: release
    secrets: inherit
  release:
    runs-on: depot-ubuntu-22.04-4
    name: Release
    needs: build_binary
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Nix
        uses: hoprnet/hopr-workflows/actions/setup-nix@setup-nix-v1
        with:
          cachix_cache_name: gnosis-vpn
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Display versions
        run: |
          echo "- Package version: v${{ needs.build_binary.outputs.GNOSISVPN_PACKAGE_VERSION }}" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "- Client version: v${{ needs.build_binary.outputs.GNOSISVPN_CLIENT_VERSION }}" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "- App version: v${{ needs.build_binary.outputs.GNOSISVPN_APP_VERSION }}" | tee -a "$GITHUB_STEP_SUMMARY"
      - name: Generate Release Notes
        run: nix develop -c ./scripts/generate-changelog.ts
        env:
          GH_TOKEN: ${{ github.token }}
          GNOSISVPN_PACKAGE_VERSION: ${{ needs.build_binary.outputs.GNOSISVPN_PACKAGE_VERSION }}
          GNOSISVPN_CLIENT_VERSION: ${{ needs.build_binary.outputs.GNOSISVPN_CLIENT_VERSION }}
          GNOSISVPN_APP_VERSION: ${{ needs.build_binary.outputs.GNOSISVPN_APP_VERSION }}
          GNOSISVPN_PREVIOUS_PACKAGE_VERSION: ${{ vars.GNOSISVPN_PACKAGE_RELEASE_VERSION }}
          GNOSISVPN_PREVIOUS_CLIENT_VERSION: ${{ vars.GNOSISVPN_CLIENT_RELEASE_VERSION }}
          GNOSISVPN_PREVIOUS_APP_VERSION: ${{ vars.GNOSISVPN_APP_RELEASE_VERSION }}
          GNOSISVPN_CHANGELOG_FORMAT: github
      - name: Release version
        uses: hoprnet/hopr-workflows/actions/release-version@release-version-v3
        with:
          source_branch: ${{ github.ref_name }}
          file: package.json
          release_type: ${{ inputs.release_type }}
          cachix_cache_name: gnosis-vpn
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          zulip_api_key: ${{ secrets.ZULIP_API_KEY }}
          zulip_email: ${{ secrets.ZULIP_EMAIL }}
          zulip_channel: GnosisVPN
          zulip_topic: Releases
          gcp_service_account: ${{ secrets.GCP_SA_GITHUB_ACTIONS }}
          gcp_artifact_package: gnosis_vpn
          release_notes_file: ./build/changelog/changelog
          github_token: ${{ secrets.BOT_TOKEN }}
      - name: Bump Version
        id: bump
        shell: bash
        run: |
          gh variable set GNOSISVPN_PACKAGE_RELEASE_VERSION --body "${{ needs.build_binary.outputs.GNOSISVPN_PACKAGE_VERSION }}"
          gh variable set GNOSISVPN_CLIENT_RELEASE_VERSION --body "${{ needs.build_binary.outputs.GNOSISVPN_CLIENT_VERSION }}"
          gh variable set GNOSISVPN_APP_RELEASE_VERSION --body "${{ needs.build_binary.outputs.GNOSISVPN_APP_VERSION }}"
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
