name: Update Manifests
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Close release
      - Snapshot Build
    types:
      - completed
    branches:
      - main
concurrency:
  group: update-manifests
  cancel-in-progress: false
jobs:
  update_manifests:
    runs-on: depot-ubuntu-22.04-4
    name: Update Manifests
    permissions:
      contents: read
      actions: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@eedb4b7701714299852ca5243f1544b817653f33 # hopr-workflows v0.11.1
      - name: Setup GCP
        uses: hoprnet/hopr-workflows/actions/setup-gcp@eedb4b7701714299852ca5243f1544b817653f33 # hopr-workflows v0.11.1
        with:
          workload_identity_provider: projects/656686060169/locations/global/workloadIdentityPools/gnosisvpn-gh-pool/providers/github-provider
          service_account: download-gnosisvpn-gh-sa@gnosisvpn-production.iam.gserviceaccount.com
          install_sdk: true
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Generate GitHub App token
        id: bot-token
        uses: actions/create-github-app-token@eedb4b7701714299852ca5243f1544b817653f33 # hopr-workflows v0.11.1
        with:
          client-id: ${{ secrets.GH_APP_GNOSISVPN_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_GNOSISVPN_BOT_PRIVATE_KEY }}
          owner: gnosis
      - name: Generate update manifests
        run: bash ./scripts/generate-update-manifest.sh
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
          OUTPUT_DIR: ./build/manifests
      - name: Sign manifests
        uses: hoprnet/hopr-workflows/actions/sign-file@eedb4b7701714299852ca5243f1544b817653f33 # hopr-workflows v0.11.1
        with:
          path: ./build/manifests
          architecture: x86_64-linux
          gpg_private_key: ${{ secrets.GNOSISVPN_GPG_PRIVATE_KEY }}
          gpg_private_key_password: ${{ secrets.GNOSISVPN_GPG_PRIVATE_KEY_PASSWORD }}
      - name: List manifests folder
        run: ls -la ./build/manifests
      - name: Upload manifests artifact
        uses: actions/upload-artifact@eedb4b7701714299852ca5243f1544b817653f33 # hopr-workflows v0.11.1
        with:
          name: manifests
          path: ./build/manifests
          if-no-files-found: error
      - name: Publish manifests to bucket
        uses: google-github-actions/upload-cloud-storage@eedb4b7701714299852ca5243f1544b817653f33 # hopr-workflows v0.11.1
        with:
          path: ./build/manifests
          destination: download.gnosisvpn.io
          process_gcloudignore: false
      - name: Set cache control
        run: gsutil -m setmeta -h "Cache-Control:no-cache, no-store, must-revalidate" "gs://download.gnosisvpn.io/manifests/**"
